image:
  name: "ghcr.io/gopaytech/internal-access-helper"
  tag: "v1.1.0"

pullPolicy: "Always"
podLabels: {}
imagePullSecrets: []

argoCDNamespace: "argocd"
argoCDManagerSecretName: "argocd-manager"
disableFeatures: false

resources:
  requests:
    cpu: 128m
    memory: 128Mi
  limits:
    cpu: 256m
    memory: 256Mi
